"""Domain models for PRAMAAN. Importing this package registers every model
on ``Base.metadata`` (needed by schema creation and reset tooling)."""

from app.models.domain import (
    Application,
    ApplicationStatus,
    AuditEvent,
    Challenge,
    ChallengeStatus,
    Department,
    Evaluation,
    Evidence,
    EvidenceCheck,
    Measurement,
    MilestoneStatus,
    PaymentStatus,
    Pilot,
    PilotMilestone,
    PilotRisk,
    PilotStatus,
    Protocol,
    ProtocolStatus,
    ReuseAction,
    ReuseDecision,
    ScaleDecision,
    ScaleOutcome,
    Startup,
    Validation,
    ValidationStatus,
    Verdict,
    VerdictOutcome,
    Vpr,
    VprStatus,
)

__all__ = [
    "Application",
    "ApplicationStatus",
    "AuditEvent",
    "Challenge",
    "ChallengeStatus",
    "Department",
    "Evaluation",
    "Evidence",
    "EvidenceCheck",
    "Measurement",
    "MilestoneStatus",
    "PaymentStatus",
    "Pilot",
    "PilotMilestone",
    "PilotRisk",
    "PilotStatus",
    "Protocol",
    "ProtocolStatus",
    "ReuseAction",
    "ReuseDecision",
    "ScaleDecision",
    "ScaleOutcome",
    "Startup",
    "Validation",
    "ValidationStatus",
    "Verdict",
    "VerdictOutcome",
    "Vpr",
    "VprStatus",
]
